### ISSUE TITLE
Recompose definitions cause flow-typed install to fail

### ISSUE THREAD

**Issue by dpca** [flowtype/flow-typed#1035]
I think the recompose folder name is improperly formatted, from the looks of my trace it's probably the trailing `-`. Perhaps changing the folder to `recompose_v0.24.x` would fix it?

Trace:
```
yarn run v0.27.5
$ flow-typed install
• Found 33 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: TypeError: Invalid comparator: ^v0.24.x-
    at Comparator.parse (.../node_modules/semver/semver.js:678:11)
    at new Comparator (.../node_modules/semver/semver.js:662:8)
    at .../node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (.../node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (.../node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (.../node_modules/semver/semver.js:720:40)
    at pkgVersionMatch (.../node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:309:21)
    at .../node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:333:82
```

In package.json I have:
```
    "flow-bin": "^0.49.1",
    "flow-typed": "^2.1.2",
    "recompose": "^0.24.0",
```

**Comment by GAntoine** [comment]
There's an [open PR](https://github.com/flowtype/flow-typed/pull/1034) to fix this.
