### ISSUE TITLE
cannot find module jest-cli on cli tool

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1066]
Error: Cannot find module '/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest-cli'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at getJest (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:22:12)
    at Object.run (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/build/cli/index.js:39:48)
    at Object.<anonymous> (/Users/sibelius/Dev/me/flow-typed/cli/node_modules/jest/node_modules/jest-cli/bin/jest.js:14:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by GAntoine** [comment]
@sibelius Were you able to get this working eventually?

**Comment by sibelius** [comment]
Only installing jest-cli as well

**Comment by GAntoine** [comment]
Thanks for the update, in that case I'm going to re-open the issue.

**Comment by sibelius** [comment]
I think we can close in fact, it is not that bad. I’ll try again with latest version, tks
