### ISSUE TITLE
Install flow-typed error on forked dependencies 

### ISSUE THREAD

**Issue by AndreiCalazans** [flowtype/flow-typed#1124]
flow-typed install is giving me an error for this dependency
**"react-select": "git+https://git@github.com/lucasbento/react-select.git",**

`MacBookPro:feedback-admin staff$ flow-typed install
• Found 62 dependencies in package.json to install libdefs for. Searching...
• flow-typed cache not found, fetching from GitHub...
UNCAUGHT ERROR: TypeError: Invalid comparator: git+https://git@github.com/lucasbento/react-select.git
    at Comparator.parse (/Users/staff/.config/yarn/global/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/staff/.config/yarn/global/node_modules/semver/semver.js:662:8)
    at /Users/staff/.config/yarn/global/node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (/Users/staff/.config/yarn/global/node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (/Users/staff/.config/yarn/global/node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (/Users/staff/.config/yarn/global/node_modules/semver/semver.js:720:40)
    at pkgVersionMatch (/Users/staff/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:328:18)
    at /Users/staff/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:353:82
`

Am i missing something here ?

**Comment by GAntoine** [comment]
No, unfortunately `flow-typed` does not support package versions with prefixes (`git+`, `github:`). Since code layout and package versioning is strongly based around semver (x.x.x), it's difficult to infer the version from a line like `"react-select": "git+https://git@github.com/lucasbento/react-select.git"`

Related: #895

**Comment by marudor** [comment]
#1127 Feature Issue for this.
