### ISSUE TITLE
flow-typed 2.2.0 failing to start on Windows platform

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#1350]
After upgrading to 2.2.0 I get the following error message when trying to run it on the Windows platform:

```
node_modules\.bin\flow-typed install
node_modules\flow-typed\dist\commands\runTests.js:70
var basePathRegex = new RegExp('definitions' + _node.path.sep + 'npm' + _node.path.sep + '(@[^' + _node.path.sep + ']*' + _node.path.sep + ')?[^' + _node.path.s
ep + ']*' + _node.path.sep + '?');
                    ^

SyntaxError: Invalid regular expression: /definitions\npm\(@[^\]*\)?[^\]*\?/: Unterminated character class
    at RegExp (<anonymous>)
    at Object.<anonymous> (node_modules\flow-typed\dist\commands\runTests.js:70:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules\flow-typed\dist\cli.js:26:17)

```

**Comment by kyrylkov** [comment]
It's a know issue.  Alas ignored for almost a week: https://github.com/flowtype/flow-typed/issues/1313

**Comment by doberkofler** [comment]
@kyrylkov Thank you!

**Comment by GAntoine** [comment]
It's been fixed on master, but yeah we're waiting on a release to npm. Should be coming soon.

**Comment by usiyalla** [comment]
+1

**Comment by danilo-s-coelho** [comment]
+1

**Comment by budarin** [comment]
is it released?
I'm steel have this bug

**Comment by GAntoine** [comment]
Not yet, I'll let everyone know when it does.

**Comment by GAntoine** [comment]
Good news, 2.2.1 was just released on npm.

**Comment by budarin** [comment]
@GAntoine  thanks!
