### ISSUE TITLE
TypeError: Invalid Version: ow-v0.24.2

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1519]
when running `run_def_tests.sh`

**Comment by GAntoine** [comment]
Weird, I just fetched and I'm not getting that error. What's the exact command you're running?

**Comment by XaveScor** [comment]
I have the some error in debian/windows10/windows10WSL.

**Comment by GAntoine** [comment]
@XaveScor Could you post the error message?

**Comment by XaveScor** [comment]
@GAntoine 
```
UNCAUGHT ERROR: TypeError: Invalid Version: 0.30.0.zip
    at new SemVer (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\semver\semver.js:2
93:11)
    at compare (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\semver\semver.js:566:
10)
    at Object.lt (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\semver\semver.js:60
0:10)
    at C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\dist\commands\runTests.js:412:27
    at Array.sort (native)
    at Array.sort (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\core-js\modules\es
6.array.sort.js:21:15)
    at getCachedFlowBinVersions$ (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\dist\commands\ru
nTests.js:411:20)
    at tryCatch (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\
runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules
\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\andrey.vassilyev\AppData\Roaming\npm\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:117:21)
```

**Comment by XaveScor** [comment]
```
UNCAUGHT ERROR: TypeError: Invalid Version: ow-v0.36.0
cli.js:58
    at new SemVer (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:293:11)
    at compare (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:566:10)
    at Object.lt (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:600:10)
    at c:\Users\andrey.vassilyev\projects\flow-typed\cli\dist\commands\runTests.js:409:27
    at Array.sort (native)
    at Array.sort (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\core-js\modules\es6.array.sort.js:21:15)
    at getCachedFlowBinVersions$ (c:\Users\andrey.vassilyev\projects\flow-typed\cli\dist\commands\runTests.js:408:20)
    at tryCatch (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\regenerator-runtime\runtime.js:116:21)
```
8 hours ago )

**Comment by XaveScor** [comment]
@GAntoine sorry. The error is gone. I found the other error. Check the #1577

**Comment by GAntoine** [comment]
Ok, I'm gonna close this issue and we can move the conversation to 1577.
