### ISSUE TITLE
Cannot get tests to run on windows

### ISSUE THREAD

**Issue by lukeapage** [flowtype/flow-typed#1976]
I'd like to contribute but I'm having trouble getting things working.

I'm on windows 10, I've tried git bash, cmd and powershell.

I've updated git, updated node, tried with yarn or npm.

first.. tests fail:

```
    Unable to find `git` installed on this system: not found: git

      124 | }
      125 |
    > 126 | export async function rebaseRepoMaster(repoDirPath: string) {
      127 |   const gitPath = await getGitPath();
      128 |   await child_process
      129 |     .spawnP(gitPath, ['checkout', 'master'], {cwd: repoDirPath})

      at getGitPath$ (src/lib/git.js:126:583)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:152:20)
      at node_modules/regenerator-runtime/runtime.js:164:13
```

and then slow downloads and unzips but the files then get deleted before they are run (I watched the folder to confirm):

```
Fetching all Flow binaries...
==========================================================================================
We are tempoarily skipping v0.67.0 due to https://github.com/facebook/flow/issues/5922
==========================================================================================
  Fetching flow-v0.68.0...
  Fetching flow-v0.67.1...
  Fetching flow-v0.66.0...
  Fetching flow-v0.65.0...
  Fetching flow-v0.64.0...
  Fetching flow-v0.63.1...
  Fetching flow-v0.63.0...
  Fetching flow-v0.62.0...
  Fetching flow-v0.61.0...
  Fetching flow-v0.60.1...
  Fetching flow-v0.60.0...
  Fetching flow-v0.59.0...
  Fetching flow-v0.58.0...
  Fetching flow-v0.57.3...
    flow-v0.58.0 finished downloading.
  Extracting flow-v0.58.0...
    flow-v0.65.0 finished downloading.
  Extracting flow-v0.65.0...
  Removing flow-v0.58.0 artifacts...
    flow-v0.58.0 complete!
  Removing flow-v0.65.0 artifacts...
    flow-v0.65.0 complete!
    flow-v0.62.0 finished downloading.
  Extracting flow-v0.62.0...
  Removing flow-v0.62.0 artifacts...
    flow-v0.62.0 complete!
    flow-v0.60.0 finished downloading.
  Extracting flow-v0.60.0...
    flow-v0.63.1 finished downloading.
  Extracting flow-v0.63.1...
    flow-v0.60.1 finished downloading.
  Extracting flow-v0.60.1...
    flow-v0.61.0 finished downloading.
  Extracting flow-v0.61.0...
  Removing flow-v0.60.0 artifacts...
    flow-v0.60.0 complete!
  Removing flow-v0.63.1 artifacts...
    flow-v0.63.1 complete!
  Removing flow-v0.60.1 artifacts...
    flow-v0.60.1 complete!
  Removing flow-v0.61.0 artifacts...
    flow-v0.61.0 complete!
    flow-v0.63.0 finished downloading.
  Extracting flow-v0.63.0...
    flow-v0.66.0 finished downloading.
  Extracting flow-v0.66.0...
  Removing flow-v0.63.0 artifacts...
    flow-v0.63.0 complete!
  Removing flow-v0.66.0 artifacts...
    flow-v0.66.0 complete!
    flow-v0.67.1 finished downloading.
  Extracting flow-v0.67.1...
  Removing flow-v0.67.1 artifacts...
    flow-v0.67.1 complete!
    flow-v0.68.0 finished downloading.
  Extracting flow-v0.68.0...
  Removing flow-v0.68.0 artifacts...
    flow-v0.68.0 complete!
    flow-v0.57.3 finished downloading.
  Extracting flow-v0.57.3...
  Removing flow-v0.57.3 artifacts...
    flow-v0.57.3 complete!
    flow-v0.59.0 finished downloading.
  Extracting flow-v0.59.0...
  Removing flow-v0.59.0 artifacts...
    flow-v0.59.0 complete!
    flow-v0.64.0 finished downloading.
  Extracting flow-v0.64.0...
  Removing flow-v0.64.0 artifacts...
    flow-v0.64.0 complete!
Finished fetching Flow binaries.

Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.57.3)...
Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.58.0)...
Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.59.0)...
Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.60.0)...
Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.60.1)...
Testing react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.61.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.62.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.63.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.63.1)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.64.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.65.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.66.0)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.67.1)...
Testing react-redux_v5.x.x/flow_v0.62.0- (flow-v0.68.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.57.3)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.58.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.59.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.60.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.60.1)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.61.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.62.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.63.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.63.1)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.64.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.65.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.66.0)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.67.1)...
Testing react-redux_v4.x.x/flow_v0.53.x- (flow-v0.68.0)...

ERROR: react-redux_v5.x.x/flow_v0.54.x-v0.61.x
 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.59.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.59.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.58.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.58.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.57.3): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.57.3' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.60.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.60.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.60.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.60.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.54.x-v0.61.x (flow-v0.61.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.61.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

ERROR: react-redux_v5.x.x/flow_v0.62.0-
 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.63.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.63.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.63.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.63.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.62.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.62.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.64.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.64.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.65.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.65.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.66.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.66.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.67.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.67.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v5.x.x/flow_v0.62.0- (flow-v0.68.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.68.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

ERROR: react-redux_v4.x.x/flow_v0.53.x-
 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.59.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.59.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.58.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.58.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.57.3): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.57.3' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.60.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.60.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.60.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.60.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.63.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.63.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.62.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.62.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.61.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.61.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.63.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.63.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.64.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.64.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.66.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.66.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.65.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.65.0' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.67.1): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.67.1' is not recognized as an internal or external command,
   operable program or batch file.

   null

 * react-redux_v4.x.x/flow_v0.53.x- (flow-v0.68.0): Unexpected Flow errors(1):
   'C:\git\flow-typed\cli\.flow-bins-cache\flow-v0.68.0' is not recognized as an internal or external command,
   operable program or batch file.

   null
```

**Comment by lukeapage** [comment]
unable to find git is just because cmd and powershell don't have which. Switching back to git bash now passes the tests (not sure if it was upgrading tests for having binaries in the cache). So the PR linked fixes the issues for me.
