### ISSUE TITLE
React-navigation makes `flow-typed install` fail

### ISSUE THREAD

**Issue by maxencefrenette** [flowtype/flow-typed#2048]
Hi, when trying to install new typings for my project, I get an error caused by react-navigation having a CONTRIBUTING.md file in their folder.

```
Maxence-VirtualBox% flow-typed install
• Found 29 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.
    at validationError (/home/maxence/.config/yarn/global/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /home/maxence/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/home/maxence/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:95:23)
    at tryCatch (/home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:155:20)
    at /home/maxence/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:165:13
```

I see two solutions to this. Either support having a CONTRIBUTING.md in the type definitions folders or delete react-nativation's CONTRIBUTING.md. What do you guys think ?

**Comment by GAntoine** [comment]
This is already supported. You'll need to update to the latest version of `flow-typed`.

**Comment by IanVS** [comment]
It seems the latest version is `2.4.0`, which I have tried, and `flow-typed install` is still failing for this reason.  What version are you referring to that works, @GAntoine?

**Comment by AndrewSouthpaw** [comment]
Can you verify there's no mixup about local vs. global installs and which version is being used?

**Comment by AndrewSouthpaw** [comment]
No worries. The nuance of `yarn global add <x>` when it was previously installed with npm trips up all of us.
