### ISSUE TITLE
Error: react-navigation_v1.x.x/CONTRIBUTING.md

### ISSUE THREAD

**Issue by Inzephirum** [flowtype/flow-typed#2121]
Error when installing

```flow-typed install -s
• Found 70 dependencies in package.json to install libdefs for. Searching...
UNCAUGHT ERROR: Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.
    at validationError (/usr/local/share/.config/yarn/global/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /usr/local/share/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/usr/local/share/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:95:23)
    at tryCatch (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:155:20)
    at /usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:165:13```

**Comment by GAntoine** [comment]
Thanks @saadq!

**Comment by AndrewSouthpaw** [comment]
#pleaseSearchIssuesBeforeFiling 😂
