### ISSUE TITLE
error installing flow typed

### ISSUE THREAD

**Issue by kasperpeulen** [flowtype/flow-typed#331]
I tried installing flow-typed, but I got this error:

```
Kasper@Kaspers-MacBook-Pro:~/Code/playground/firebase-react|
⇒  npm install -g flow-typed
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> nodegit@0.15.1 preinstall /Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2/configure --with-libssl-prefix=/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/openssl/openssl
configure: error: in `/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2/configure --with-libssl-prefix=/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/openssl/openssl' }
configure: error: in `/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2/configure --with-libssl-prefix=/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/openssl/openssl
configure: error: in `/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/libssh2/configure --with-libssl-prefix=/Users/Kasper/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-eb00896b/vendor/openssl/openssl' }
/Users/Kasper/.nvm/versions/node/v6.6.0/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/Kasper/.nvm/versions/node/v6.6.0/bin/node" "/Users/Kasper/.nvm/versions/node/v6.6.0/bin/npm" "install" "-g" "flow-typed"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Kasper/Code/playground/firebase-react/npm-debug.log
npm ERR! code 1
```

**Comment by AlicanC** [comment]
Try `brew install openssl`.

**Comment by kasperpeulen** [comment]
@AlicanC thanks works :)

**Comment by jeffmo** [comment]
Over in https://github.com/flowtype/flow-typed/commit/2e376ddee182ea586ecb0a7cb8e62212f0e304bc I dropped the dependency on `nodegit` in favor of a tiny API I made that just shells out to the `git` command indirectly. This seems to work and also fixes some windows compat issues -- so hopefully we shouldn't see this class of error again.

Thanks for the report!
