### ISSUE TITLE
[Solved] Error install flow-typed on Mac OS 10.11.6

### ISSUE THREAD

**Issue by ctrlplusb** [flowtype/flow-typed#336]
```
$ npm i flow-typed@2.0.0-beta.9 -g
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> nodegit@0.15.1 preinstall /Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/libssh2/configure --with-libssl-prefix=/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/libssh2/configure --with-libssl-prefix=/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/openssl/openssl' }
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/libssh2/configure --with-libssl-prefix=/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/libssh2/configure --with-libssl-prefix=/Users/sean/.nvm/versions/node/v6.6.0/lib/node_modules/.staging/nodegit-af44277b/vendor/openssl/openssl' }
/Users/sean/.nvm/versions/node/v6.6.0/lib
└── (empty)
```

**Comment by ctrlplusb** [comment]
I tried to brew install openssl, but...

```
This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries
```

**Comment by ctrlplusb** [comment]
Does work after running

`brew install libgcrypt`

**Comment by ctrlplusb** [comment]
Leaving this up here for anyone else.

**Comment by jeffmo** [comment]
Thanks, @ctrlplusb. I think this would be a good thing to go into an FAQs section of the README. I'll add this there and then close this out

**Comment by jeffmo** [comment]
Ok, I've added an FAQs section over here with this issue listed.
Thanks again for the report!
