### ISSUE TITLE
Installation dies when packages.json references git

### ISSUE THREAD

**Issue by thomasj02** [flowtype/flow-typed#367]
After doing `npm install lru-cache` my packages.json has this line:

`"lru-cache": "git://github.com/isaacs/node-lru-cache.git#96ff17f5fff170cf9288e9ff73ab472eed2f62a5",`

Running `flow-typed install` complains:

```
• rebasing flow-typed cache...done.
UNCAUGHT ERROR: TypeError: Invalid comparator: git://github.com/isaacs/node-lru-cache.git#96ff17f5fff170cf9288e9ff73ab472eed2f62a5
    at Comparator.parse (/usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:678:11)
    at new Comparator (/usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:662:8)
    at /usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (/usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (/usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (/usr/lib/node_modules/flow-typed/node_modules/semver/semver.js:720:40)
    at libdefMatchesPackageVersion (/usr/lib/node_modules/flow-typed/dist/lib/libDefs.js:978:18)
    at /usr/lib/node_modules/flow-typed/dist/lib/libDefs.js:1004:72

```

**Comment by jeffmo** [comment]
There's not much we can do from a versioning standpoint with a github repo right now, but at minimum we should warn/not fatal.

Thanks for the report!

**Comment by GAntoine** [comment]
Closing in favour of the new feature issue at #1127.
