### ISSUE TITLE
flow-typed install does not support package.json with same dependency in dev dependencies and peer dependencies

### ISSUE THREAD

**Issue by relekang** [flowtype/flow-typed#423]
Having peer dependencies in dev dependencies is as far as i know a common thing to do. It would be good to support this.

I will try to make a PR to fix this.

package.json example for reproducing error:

``` json
{
  "name": "Test project",
  "version": "1.0.0",
  "devDependencies": {
    "flow-bin": "^0.34.0",
    "react": "^15.3.2"
  },
  "peerDependencies": {
    "react": "^15.3.2"
  }
}
```

Error output from flow:

```
Found flow-bin@v0.34.0 installed. Installing libdefs compatible with this version of Flow...
UNCAUGHT ERROR: Error: Found react listed twice in package.json!
    at ~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:123:17
    at Array.forEach (native)
    at ~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:121:35
    at Array.reduce (native)
    at getPackageJsonDependencies (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:118:30)
    at Object.run$ (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/dist/commands/install.js:177:91)
    at tryCatch (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:95:21)
    at tryCatch (~/.nvm/versions/node/v6.5.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:62:40)
```

**Comment by ahutchings** [comment]
Also reported in #379.

**Comment by relekang** [comment]
I missed that issue somehow. Thanks for letting me know.
