### ISSUE TITLE
support namespaced npm packages

### ISSUE THREAD

**Issue by capaj** [flowtype/flow-typed#671]
so I have:

```
"@capaj/trae": "1.1.2",
```

in my deps

and when I run:
```
> flow-typed install

• Found flow-bin@v0.38.0 installed. Installing libdefs compatible with this version of Flow...
• Found 113 dependencies in package.json. Searching for libdefs...
• rebasing flow-typed cache...done.
• Installing 16 libdefs...
  • enzyme_v2.3.x.js
    └> ./flow-typed/npm/enzyme_v2.3.x.js
  • flow-bin_v0.x.x.js
    └> ./flow-typed/npm/flow-bin_v0.x.x.js
  • chalk_v1.x.x.js
    └> ./flow-typed/npm/chalk_v1.x.x.js
  • chai_v3.5.x.js
    └> ./flow-typed/npm/chai_v3.5.x.js
  • uuid_v3.x.x.js
    └> ./flow-typed/npm/uuid_v3.x.x.js
  • object-assign_v4.x.x.js
    └> ./flow-typed/npm/object-assign_v4.x.x.js
  • react-dnd-html5-backend_v2.1.x.js
    └> ./flow-typed/npm/react-dnd-html5-backend_v2.1.x.js
  • react-dnd_v2.x.x.js
    └> ./flow-typed/npm/react-dnd_v2.x.x.js
  • moment_v2.x.x.js
    └> ./flow-typed/npm/moment_v2.x.x.js
  • lodash_v4.x.x.js
    └> ./flow-typed/npm/lodash_v4.x.x.js
  • isomorphic-fetch_v2.x.x.js
    └> ./flow-typed/npm/isomorphic-fetch_v2.x.x.js
  • classnames_v2.x.x.js
    └> ./flow-typed/npm/classnames_v2.x.x.js
  • axios_v0.15.x.js
    └> ./flow-typed/npm/axios_v0.15.x.js
  • react-addons-test-utils_v15.x.x.js
    └> ./flow-typed/npm/react-addons-test-utils_v15.x.x.js
  • jest_v18.x.x.js
    └> ./flow-typed/npm/jest_v18.x.x.js
  • strip-ansi_v3.x.x.js
    └> ./flow-typed/npm/strip-ansi_v3.x.x.js
UNCAUGHT ERROR: Error: Unable to find `node_modules/trae/` install directory! Did you forget to run `npm install` before running `flow-typed install`?
    at resolvePkgDirPath$ (/tmp/frontend-stage-bee-release/node_modules/flow-typed/dist/lib/stubUtils.js:91:17)
    at tryCatch (/tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:154:20)
    at /tmp/frontend-stage-bee-release/node_modules/regenerator-runtime/runtime.js:164:13

```

This happens. It should look for the module under @capaj dir, not in `node_modules/trae/`

**Comment by capaj** [comment]
so after a couple more tries, the problem seems to be that npm does not install that module when it is specified by a url(it was working well with a namespaced module dependency). So the error is right and the module was in fact missing. Therefore closing
