### ISSUE TITLE
Running flow on appveyor fails

### ISSUE THREAD

**Issue by arekkas** [flowtype/flow-typed#679]
I'm unable to get flow running on appveyor. I'm using `"flow-bin": "^0.40.0",`. Any tips?

```
> ory-sites-app@0.0.0 flow C:\projects\sites-app
> flow check --show-all-errors
C:\projects\sites-app\node_modules\flow-bin\cli.js:20
  throw new Error('Platform not supported.');
  ^
Error: Platform not supported.
    at Object.<anonymous> (C:\projects\sites-app\node_modules\flow-bin\cli.js:20:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "flow"
```

**Comment by arekkas** [comment]
see https://github.com/flowtype/flow-bin/issues/50
