### ISSUE TITLE
Error: event-to-promise_v0.7.0-: 'event-to-promise_v0.7.0-' is a malformed definitions/npm/ directory name!

### ISSUE THREAD

**Issue by capaj** [flowtype/flow-typed#718]
I started getting this:
```
UNCAUGHT ERROR: Error: event-to-promise_v0.7.0-: 'event-to-promise_v0.7.0-' is a malformed definitions/npm/ directory name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH>
    at validationError (/home/capaj/git_projects/be/frontend-be.com/node_modules/flow-typed/dist/lib/libDefs.js:804:11)
    at parseRepoDirItem (/home/capaj/git_projects/be/frontend-be.com/node_modules/flow-typed/dist/lib/libDefs.js:731:5)
    at addLibDefs$ (/home/capaj/git_projects/be/frontend-be.com/node_modules/flow-typed/dist/lib/libDefs.js:304:27)
    at tryCatch (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:154:20)
    at /home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:201:11
    at callInvokeWithMethodAndArg (/home/capaj/git_projects/be/frontend-be.com/node_modules/regenerator-runtime/runtime.js:200:16)

```

Could it be raleted to this commit? https://github.com/flowtype/flow-typed/commit/7d51177186ad8bd2b30d2541a4d788b1d1f9c58f

I suspect so @philikon.
Also could flow-typed skip these errors in the future with only a warning?

**Comment by smagch** [comment]
I've just run into the same error when I try to run `flow-typed install` or `flow-typed search`.

It seems there were similar issue before, #652 and #610 . It'd be much nicer to skip the error instead of halting with crash.

**Comment by abisz** [comment]
Is there a way to quickly bypass this or are we completely blocked until this is fixed?

**Comment by marudor** [comment]
Fixed.
