### ISSUE TITLE
UNCAUGHT ERROR: TypeError: Invalid comparator: test

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#786]
• Found flow-bin@v0.44.0 installed. Installing libdefs compatible with this version of Flow...
• Found 33 dependencies in package.json. Searching for libdefs...
```
UNCAUGHT ERROR: TypeError: Invalid comparator: test
    at Comparator.parse (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:678:11)
    at new Comparator (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:662:8)
    at /Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:780:12
    at Array.map (native)
    at Range.parseRange (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:779:13)
    at Range.<anonymous> (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:721:17)
    at Array.map (native)
    at new Range (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/node_modules/semver/semver.js:720:40)
    at libdefMatchesPackageVersion (/Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:978:18)
    at /Users/sibelius/.nvm/versions/node/v6.10.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:1004:72
```

this could be similar to https://github.com/flowtype/flow-typed/issues/399

my package.json (https://github.com/entria/graphql-dataloader-boilerplate)

```json
{
  "name": "graphql-dataloader-boilerplate",
  "description": "GraphQL DataLoader boilerplate",
  "version": "0.0.1",
  "dependencies": {
    "babel-polyfill": "^6.23.0",
    "bcrypt-as-promised": "^1.1.0",
    "dataloader": "^1.3.0",
    "dotenv-safe": "^4.0.3",
    "graphql": "^0.9.3",
    "graphql-relay": "^0.5.1",
    "isomorphic-fetch": "^2.2.1",
    "jsonwebtoken": "^7.3.0",
    "koa": "^2.2.0",
    "koa-bodyparser": "^4.2.0",
    "koa-compose": "^4.0.0",
    "koa-convert": "^1.2.0",
    "koa-cors": "0.0.16",
    "koa-graphql": "^0.6.2",
    "koa-logger": "^2.0.1",
    "mongoose": "^4.9.4"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-eslint": "^7.2.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-stage-0": "^6.24.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "flow-bin": "^0.44.0",
    "jest": "test",
    "jest-cli": "test",
    "nodemon": "^1.10.2",
    "reify": "^0.7.4",
    "repl": "^0.1.3",
    "repl-promised": "^0.1.0",
    "repl.history": "^0.1.4",
    "rimraf": "^2.6.1"
  },
  "jest": {
    "testEnvironment": "node",
    "testPathIgnorePatterns": [
      "/node_modules/",
      "./dist"
    ],
    "coverageReporters": [
      "lcov",
      "html"
    ],
    "coverageDirectory": "./coverage/",
    "collectCoverage": true,
    "moduleNameMapper": {
      "^mongoose$": "<rootDir>/node_modules/mongoose"
    }
  },
  "license": "MIT",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/sibelius/graphql-dataloader-boilerplate"
  },
  "scripts": {
    "build": "npm run clear && babel src --ignore *.spec.js --out-dir dist --copy-files",
    "clear": "rimraf ./dist",
    "flow": "flow; test $? -eq 0 -o $? -eq 2",
    "lint": "eslint src/**",
    "repl": "nodemon --config ./repl/nodemon.json ./repl.js --exec babel-node",
    "start": "node dist/index.js",
    "test": "jest --coverage --forceExit --runInBand",
    "test:watch": "jest --watch --coverage",
    "update-schema": "babel-node ./scripts/updateSchema.js",
    "watch": "nodemon src/index.js --exec babel-node"
  }
}
```

**Comment by sibelius** [comment]
I've found the issue

jest package was in `test` version

I think this should be marked as a bug

**Comment by jeffmo** [comment]
Thanks for the report, I'll take a look at this soon.
