### ISSUE TITLE
Unable to update existing flow-typed libs: The major version of a Flow version string cannot be `x`

### ISSUE THREAD

**Issue by EvHaus** [flowtype/flow-typed#794]
I had `flow-typed@2.0.0` installed with some libdefs already installed. I then upgraded to `flow-typed@2.1.1` and wanted to install the updated libdefs.

I tried: `./node_modules/.bin/flow-typed install` and that gave me the following error:

```
• Found 107 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: vx.x.x: The major version of a Flow version string cannot be `x`, it must be a number!
    at validationError (/Users/evgueni.naverniouk/Git/web-platform/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at _parseVersion (/Users/evgueni.naverniouk/Git/web-platform/node_modules/flow-typed/dist/lib/flowVersion.js:51:45)
    at parseDirString (/Users/evgueni.naverniouk/Git/web-platform/node_modules/flow-typed/dist/lib/flowVersion.js:137:26)
    at _callee2$ (/Users/evgueni.naverniouk/Git/web-platform/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:487:147)
    at tryCatch (/Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:154:20)
    at /Users/evgueni.naverniouk/Git/web-platform/node_modules/regenerator-runtime/runtime.js:164:13
```

I then found that `flow-typed` has an `update` command, so I tried that instead `./node_modules/.bin/flow-typed update`, but that gave me the exact same error message.

The only way I was able to upgrade was to fully wipe my existing `flow-typed` directory and run `install` again.

**Comment by jeffmo** [comment]
Thanks for the report! I'll dig into this

**Comment by jeffmo** [comment]
Ok, I've found a broad set of issues in the code that's causing this, so I'm working on those now.
I need to run and catch a plane, but hopefully I can have a fix out for this soon.

In the meantime, blowing away the `flow-typed/npm/*` files is probably the best workaround (but of course be careful if you have any manually tweaked changes in there).

**Comment by jeffmo** [comment]
Ok, so that I can verify I've knocked out all cases of this: Would it be possible to send me your package.json file so I can test with it?

(or, alternatively, just all the dependencies/devDependencies/peerDeps/etc that you have listed in it)

**Comment by EvNaverniouk** [comment]
@jeffmo Yeah, no problem:

```
"dependencies": {
    "bluebird": "3.5.0",
    "bowser": "1.6.1",
    "chainable-check": "1.0.0",
    "classnames": "2.2.5",
    "dom-helpers": "3.2.1",
    "fixed-data-table": "0.6.3",
    "graphiql": "0.10.0",
    "graphql": "0.9.3",
    "i18next": "8.0.0",
    "i18next-browser-languagedetector": "1.0.1",
    "immutable": "<4.0.0",
    "ip": "1.1.5",
    "keymaster": "1.6.2",
    "less": "2.7.2",
    "moment": "2.18.1",
    "moment-timezone": "0.5.13",
    "path-to-regexp": "^1.7.0",
    "proptypes": "0.14.4",
    "qs": "6.4.0",
    "raven-js": "3.14.2",
    "react": "15.4.2",
    "react-addons-css-transition-group": "15.4.2",
    "react-addons-shallow-compare": "15.4.2",
    "react-addons-transition-group": "15.4.2",
    "react-color": "2.11.4",
    "react-dnd": "2.3.0",
    "react-dnd-html5-backend": "2.3.0",
    "react-dom": "15.4.2",
    "react-ga": "2.2.0",
    "react-grid-layout": "0.14.6",
    "react-immutable-proptypes": "2.1.0",
    "react-list": "0.8.5",
    "react-loadable": "3.3.1",
    "react-mixin": "3.0.5",
    "react-redux": "5.0.4",
    "react-router-dom": "4.1.1",
    "react-router-redux": "5.0.0-alpha.6",
    "react-virtualized": "9.7.3",
    "redux": "3.6.0",
    "redux-thunk": "2.2.0",
    "simplify-js": "1.2.1",
    "socket.io-client": "1.7.3",
    "uuid": "3.0.1",
    "whatwg-fetch": "2.0.3"
  },
  "devDependencies": {
    "autoprefixer": "6.7.7",
    "babel-cli": "6.24.1",
    "babel-core": "6.24.1",
    "babel-jest": "19.0.0",
    "babel-loader": "6.4.1",
    "babel-plugin-add-module-exports": "0.2.1",
    "babel-plugin-dynamic-import-webpack": "1.0.1",
    "babel-plugin-transform-async-to-generator": "6.24.1",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-plugin-transform-regenerator": "^6.24.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-jest": "^19.0.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "bundle-loader": "0.5.5",
    "chalk": "1.1.3",
    "check-npm-versions": "1.2.2",
    "cross-env": "4.0.0",
    "css-loader": "0.28.0",
    "css-modules-require-hook": "4.0.6",
    "enzyme": "<=2.8.0",
    "eslint-config-cumul8": "4.20.2",
    "file-api": "0.10.4",
    "file-loader": "0.11.1",
    "flow-bin": "0.44.2",
    "flow-coverage-report": "0.3.0",
    "flow-status-webpack-plugin": "^0.1.7",
    "flow-typed": "2.1.1",
    "fs-extra": "2.1.2",
    "fs-walk": "0.0.1",
    "html-loader": "0.4.5",
    "identity-obj-proxy": "3.0.0",
    "istanbul": "1.1.0-alpha.1",
    "istanbul-api": "1.1.7",
    "jasmine": "2.5.3",
    "jest": "19.0.2",
    "jsdom": "9.12.0",
    "json-loader": "0.5.4",
    "jsonlint": "ginman86/jsonlint",
    "less-loader": "4.0.3",
    "localStorage": "1.0.3",
    "markdown-loader": "2.0.0",
    "mkdirp": "0.5.1",
    "nsp": "2.6.3",
    "ora": "1.2.0",
    "postcss-less": "0.15.0",
    "postcss-loader": "1.3.3",
    "raw-loader": "0.5.1",
    "react-addons-perf": "15.4.2",
    "react-addons-test-utils": "15.4.2",
    "react-dnd-test-backend": "2.3.0",
    "react-hot-loader": "^3.0.0-beta.6",
    "style-loader": "0.16.1",
    "stylelint-config-cumul8": "1.15.0",
    "svg-react-loader": "0.3.7",
    "webpack": "2.4.1",
    "webpack-browser-plugin": "<=1.0.12",
    "webpack-bundle-analyzer": "2.4.0",
    "webpack-dev-server": "2.4.2",
    "worker-loader": "0.8.0"
  }
```

**Comment by JamieDixon** [comment]
Could these issues mentioned in comment https://github.com/flowtype/flow-typed/issues/881#issuecomment-306234713 also be related?

**Comment by NameFILIP** [comment]
Happens for me with the `clone` module:

To reproduce, run:

```
flow-typed install clone@2
```

The first two lines of the installed clone definition are:

```
// flow-typed signature: 773f32f1210fe12a75470139d919e3e8
// flow-typed version: fc57edfa32/clone_v2.x.x/flow_vx.x.x
```

This might be related to the `flow_all` folder: https://github.com/flowtype/flow-typed/tree/master/definitions/npm/clone_v2.x.x/flow_all
