### ISSUE TITLE
Running run_def_tests.cmd v2.1.2 now reporting the following new error

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#825]
running:
```
run_def_tests.cmd
```

generates this error:
```
...
> flow-typed@2.1.2 test-quick D:\MyDev\doberkofler\flow-typed\cli
> jest && npm run lint

 FAIL  src\lib\npm\__tests__\npmLibDefs-test.js
  ● npmLibDefs › getInstalledNpmLibDefs › finds unscoped libdefs

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at _callee7$ (src\lib\npm\__tests__\npmLibDefs-test.js:260:45)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:299:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:116:21)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:64:40)
      at invoke (node_modules\regenerator-runtime\runtime.js:154:20)
      at node_modules\regenerator-runtime\runtime.js:164:13

  ● npmLibDefs › getInstalledNpmLibDefs › finds scoped libdefs

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at _callee8$ (src\lib\npm\__tests__\npmLibDefs-test.js:296:45)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules\regenerator-runtime\runtime.js:299:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules\regenerator-runtime\runtime.js:116:21)
      at tryCatch (node_modules\regenerator-runtime\runtime.js:64:40)
      at invoke (node_modules\regenerator-runtime\runtime.js:154:20)
      at node_modules\regenerator-runtime\runtime.js:164:13
...
```

**Comment by GAntoine** [comment]
Closing since now fixed.
